[package]
name = "suugaku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
num-integer = "0.1.45"
unordered-pair = "0.2.4"

[dev-dependencies]
proptest = "1.0.0"
